"""Link user to account in a one-to-one relationship

Revision ID: e81168e3a2a9
Revises: c80f13180c32
Create Date: 2025-06-06 14:58:47.758866+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e81168e3a2a9'
down_revision: Union[str, None] = 'c80f13180c32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'account_id')
    # ### end Alembic commands ###
