"""Update relationships between transaction and user; update transaction type's type

Revision ID: c80f13180c32
Revises: 20250605_2039
Create Date: 2025-06-06 14:23:10.894004+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c80f13180c32'
down_revision: Union[str, None] = '20250605_2039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'type',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Enum('DEBIT', 'CREDIT', name='transaction_type'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'type',
               existing_type=sa.Enum('DEBIT', 'CREDIT', name='transaction_type'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    
    # ### end Alembic commands ###
