"""implement_one_to_one_user_account

Revision ID: b4413d847047
Revises: 2cef6fb05ef6
Create Date: 2025-06-06 15:46:25.068124+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b4413d847047'
down_revision: Union[str, None] = '2cef6fb05ef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'accounts', ['user_id'])
    op.drop_constraint(op.f('users_ibfk_1'), 'users', type_='foreignkey')
    op.drop_column('users', 'account_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_ibfk_1'), 'users', 'accounts', ['account_id'], ['id'])
    op.drop_constraint(None, 'accounts', type_='unique')
    op.alter_column('accounts', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
